<?php

namespace Sales\OrderBundle\Repository;

/**
 * SizeTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SizeTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
