<?php

namespace AppBundle\Repository;

/**
 * OrderRowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRowRepository extends \Doctrine\ORM\EntityRepository
{
}
