home_sales_order:
    resource: "@HomeSalesBundle/Controller/OrderRESTController.php"
    type: rest
    prefix: /

home_sales_shop:
    resource: "@HomeSalesBundle/Controller/ShopRESTController.php"
    type: rest
    prefix: /

home_sales_size_type:
    resource: "@HomeSalesBundle/Controller/SizeCategoryRESTController.php"
    type: rest
    prefix: /

home_sales_size:
    resource: "@HomeSalesBundle/Controller/SizeRESTController.php"
    type: rest
    prefix: /

home_sales_source:
    resource: "@HomeSalesBundle/Controller/SourceRESTController.php"
    type: rest
    prefix: /

home_sales:
    resource: "@HomeSalesBundle/Controller"
    type: annotation
    prefix: /
