sales_order_order:
    resource: "@SalesOrderBundle/Controller/OrderRESTController.php"
    type: rest
    prefix: /

sales_order_shop:
    resource: "@SalesOrderBundle/Controller/ShopRESTController.php"
    type: rest
    prefix: /

sales_order_size_type:
    resource: "@SalesOrderBundle/Controller/SizeTypeRESTController.php"
    type: rest
    prefix: /

sales_order_size:
    resource: "@SalesOrderBundle/Controller/SizeRESTController.php"
    type: rest
    prefix: /

sales_order_source:
    resource: "@SalesOrderBundle/Controller/SourceRESTController.php"
    type: rest
    prefix: /

sales_order:
    resource: "@SalesOrderBundle/Controller"
    type: annotation
    prefix: /
