services:
    home_media.uploader:
        class: Home\MediaBundle\Service\UploaderService
        arguments: ["%kernel.root_dir%"]
    home_media.transform_media_data.subscriber:
        class: Home\MediaBundle\EventSubscriber\TransformMediaDataSubscriber
        arguments: ["@home_media.uploader"]
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    home_media.serializer.subscriber:
        class: Home\MediaBundle\EventSubscriber\SerializeMediaSubscriber
        arguments: ["@request_stack"]
        tags:
            - { name: jms_serializer.event_subscriber, connection: default }