services:
    sales.order_bundle.serializer_subscriber:
        class: Sales\OrderBundle\Listener\SerializationListener
        arguments:
            - '@service_container'
        tags:
            - { name: jms_serializer.event_subscriber }

